In [1]:
import numpy as np

In [6]:
a = np.random.randint(0, high=100, size=(4,4))

In [8]:
b = np.random.randint(0, high=100, size=(4,4))

In [9]:
a

array([[ 8, 31, 89, 25],
       [36, 25, 87, 76],
       [98, 27, 20,  2],
       [58, 40, 59,  3]])

In [10]:
b

array([[65,  2, 18, 87],
       [ 5, 75, 59, 12],
       [73, 24,  5, 77],
       [61,  6, 17, 51]])

In [19]:
np.stack([a, b], axis=0).max(axis=0)

array([[65, 31, 89, 87],
       [36, 75, 87, 76],
       [98, 27, 20, 77],
       [61, 40, 59, 51]])